Repository alexweininger/android-catan, pull requests merged in 2018-11, with the labels that each got.

#26 Alex working game framework start menu
  .idea/codeStyles/codeStyleConfig.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/misc.xml
  app/src/main/java/edu/up/cs/androidcatan/Board.java
  app/src/main/java/edu/up/cs/androidcatan/CatanGameState.java
  app/src/main/java/edu/up/cs/androidcatan/CatanLocalGame.java
  app/src/main/java/edu/up/cs/androidcatan/Dice.java
  app/src/main/java/edu/up/cs/androidcatan/MainActivity.java
  app/src/main/java/edu/up/cs/androidcatan/Robber.java
  app/src/main/java/edu/up/cs/androidcatan/catan/actions/CatanBuildAction.java
  app/src/main/java/edu/up/cs/androidcatan/catan/actions/CatanTradeAction.java
  app/src/main/java/edu/up/cs/androidcatan/catan/buildings/Building.java
  app/src/main/java/edu/up/cs/androidcatan/catan/buildings/City.java
  app/src/main/java/edu/up/cs/androidcatan/catan/buildings/Road.java
  app/src/main/java/edu/up/cs/androidcatan/catan/buildings/Settlement.java
  app/src/main/java/edu/up/cs/androidcatan/catan/devcards/DevelopmentCard.java
  app/src/main/java/edu/up/cs/androidcatan/catan/graphics/House.java
  app/src/main/java/edu/up/cs/androidcatan/catan/graphics/RoadDrawable.java
  app/src/main/java/edu/up/cs/androidcatan/catan/graphics/boardSurfaceView.java
  app/src/main/java/edu/up/cs/androidcatan/catan/hexagon/Hexagon.java
  app/src/main/java/edu/up/cs/androidcatan/catan/trading/Ports.java
Labels: enhancement

#30 Andrew
  app/src/main/java/edu/up/cs/androidcatan/catan/gamestate/Board.java
  app/src/main/java/edu/up/cs/androidcatan/catan/gamestate/Port.java
Labels: feature

#41 Alex
  app/src/main/java/edu/up/cs/androidcatan/catan/CatanGameState.java
  app/src/main/java/edu/up/cs/androidcatan/catan/CatanHumanPlayer.java
  app/src/main/java/edu/up/cs/androidcatan/catan/gamestate/buildings/Building.java
Labels: bug, enhancement

#45 Alex
  .idea/dictionaries/alexw.xml
  .idea/misc.xml
  app/src/main/java/edu/up/cs/androidcatan/catan/CatanGameState.java
  app/src/main/java/edu/up/cs/androidcatan/catan/CatanHumanPlayer.java
  app/src/main/java/edu/up/cs/androidcatan/catan/CatanLocalGame.java
  app/src/main/java/edu/up/cs/androidcatan/catan/Player.java
  app/src/main/java/edu/up/cs/androidcatan/catan/actions/CatanBuildRoadAction.java
  app/src/main/java/edu/up/cs/androidcatan/catan/gamestate/Board.java
Labels: bug

#46 Alex generateHexagonTiles working
  app/src/main/java/edu/up/cs/androidcatan/catan/gamestate/Board.java
Labels: bug

#48 Alex
  app/src/main/java/edu/up/cs/androidcatan/catan/CatanComputerPlayer.java
  app/src/main/java/edu/up/cs/androidcatan/catan/CatanGameState.java
  app/src/main/java/edu/up/cs/androidcatan/catan/MainActivity.java
  app/src/main/java/edu/up/cs/androidcatan/catan/Player.java
  app/src/main/java/edu/up/cs/androidcatan/catan/gamestate/Board.java
Labels: bug

#60 Alex
  app/src/main/java/edu/up/cs/androidcatan/catan/CatanHumanPlayer.java
  app/src/main/java/edu/up/cs/androidcatan/catan/gamestate/Board.java
  app/src/main/res/layout/activity_main.xml
Labels: bug, enhancement, feature

#63 Alex aesthetic changes
  app/src/main/java/edu/up/cs/androidcatan/catan/CatanHumanPlayer.java
  app/src/main/java/edu/up/cs/androidcatan/catan/actions/CatanRollDiceAction.java
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, feature

#66 Alex build a settlement working
  .idea/misc.xml
  app/src/main/java/edu/up/cs/androidcatan/catan/CatanGameState.java
  app/src/main/java/edu/up/cs/androidcatan/catan/CatanHumanPlayer.java
  app/src/main/java/edu/up/cs/androidcatan/catan/CatanLocalGame.java
  app/src/main/java/edu/up/cs/androidcatan/catan/actions/CatanBuildRoadAction.java
  app/src/main/java/edu/up/cs/androidcatan/catan/actions/CatanBuildSettlementAction.java
  app/src/main/java/edu/up/cs/androidcatan/catan/gamestate/Board.java
  app/src/main/java/edu/up/cs/androidcatan/catan/gamestate/Hexagon.java
  app/src/main/java/edu/up/cs/androidcatan/catan/graphics/BoardSurfaceView.java
  app/src/main/java/edu/up/cs/androidcatan/catan/graphics/HexagonDrawable.java
  app/src/main/java/edu/up/cs/androidcatan/catan/graphics/HexagonGrid.java
  app/src/main/java/edu/up/cs/androidcatan/catan/graphics/boardSurfaceView.java
  app/src/main/java/edu/up/cs/androidcatan/game/LocalGame.java
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: bug

#67 Alex - dumb CPU setup phase success
  app/src/main/java/edu/up/cs/androidcatan/catan/CatanDumbComputerPlayer.java
  app/src/main/java/edu/up/cs/androidcatan/catan/CatanGameState.java
  app/src/main/java/edu/up/cs/androidcatan/catan/CatanHumanPlayer.java
  app/src/main/java/edu/up/cs/androidcatan/catan/CatanLocalGame.java
  app/src/main/java/edu/up/cs/androidcatan/catan/Player.java
  app/src/main/java/edu/up/cs/androidcatan/catan/actions/CatanBuildRoadAction.java
  app/src/main/java/edu/up/cs/androidcatan/catan/actions/CatanBuildSettlementAction.java
  app/src/main/java/edu/up/cs/androidcatan/catan/gamestate/Board.java
  app/src/main/java/edu/up/cs/androidcatan/catan/gamestate/buildings/Settlement.java
Labels: bug, enhancement, feature

#68 Alex - game graphics
  .idea/copyright/profiles_settings.xml
  app/src/main/java/edu/up/cs/androidcatan/catan/CatanDumbComputerPlayer.java
  app/src/main/java/edu/up/cs/androidcatan/catan/CatanGameState.java
  app/src/main/java/edu/up/cs/androidcatan/catan/CatanHumanPlayer.java
  app/src/main/java/edu/up/cs/androidcatan/catan/gamestate/Board.java
  app/src/main/java/edu/up/cs/androidcatan/catan/gamestate/Hexagon.java
  app/src/main/java/edu/up/cs/androidcatan/catan/gamestate/buildings/Road.java
  app/src/main/java/edu/up/cs/androidcatan/catan/graphics/BoardSurfaceView.java
  app/src/main/java/edu/up/cs/androidcatan/catan/graphics/HexagonDrawable.java
  app/src/main/java/edu/up/cs/androidcatan/catan/graphics/HexagonGrid.java
  app/src/main/res/layout/activity_main.xml
Labels: enhancement, feature

#70 Alex road intersection selection menu
  app/src/main/java/edu/up/cs/androidcatan/catan/CatanGameState.java
  app/src/main/java/edu/up/cs/androidcatan/catan/CatanHumanPlayer.java
  app/src/main/java/edu/up/cs/androidcatan/catan/graphics/HexagonDrawable.java
  app/src/main/java/edu/up/cs/androidcatan/catan/graphics/HexagonGrid.java
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/game_select_interestion_id.xml
  app/src/main/res/layout/game_select_road_id.xml
Labels: enhancement, feature

#94 Alex, merged HexagonGrid class with Niraj's
  .idea/codeStyles/codeStyleConfig.xml
  app/src/main/java/edu/up/cs/androidcatan/catan/CatanLocalGame.java
  app/src/main/java/edu/up/cs/androidcatan/catan/Player.java
  app/src/main/java/edu/up/cs/androidcatan/catan/gamestate/Board.java
  app/src/main/java/edu/up/cs/androidcatan/catan/gamestate/Hexagon.java
  app/src/main/java/edu/up/cs/androidcatan/catan/gamestate/buildings/Road.java
  app/src/main/java/edu/up/cs/androidcatan/catan/graphics/HexagonDrawable.java
  app/src/main/java/edu/up/cs/androidcatan/catan/graphics/HexagonGrid.java
  app/src/main/res/layout/game_trade_menu.xml
Labels: bug, feature

#96 Alex merge w/ Niraj
  app/src/main/java/edu/up/cs/androidcatan/catan/CatanGameState.java
  app/src/main/java/edu/up/cs/androidcatan/catan/CatanLocalGame.java
  app/src/main/java/edu/up/cs/androidcatan/catan/Player.java
  app/src/main/java/edu/up/cs/androidcatan/catan/gamestate/Board.java
  app/src/main/java/edu/up/cs/androidcatan/catan/gamestate/Hexagon.java
  app/src/main/java/edu/up/cs/androidcatan/catan/gamestate/buildings/Road.java
  app/src/main/java/edu/up/cs/androidcatan/catan/graphics/HexagonDrawable.java
  app/src/main/java/edu/up/cs/androidcatan/catan/graphics/HexagonGrid.java
Labels: feature

#100 Alex's new intersection graph generation
  app/src/main/java/edu/up/cs/androidcatan/catan/gamestate/Board.java
  app/src/main/java/edu/up/cs/androidcatan/catan/graphics/HexagonGrid.java
Labels: bug

#112 Alex spring cleaning
  .idea/dictionaries/alexw.xml
  .idea/misc.xml
  app/src/main/java/edu/up/cs/androidcatan/catan/CatanDumbComputerPlayer.java
  app/src/main/java/edu/up/cs/androidcatan/catan/CatanHumanPlayer.java
  app/src/main/java/edu/up/cs/androidcatan/catan/gamestate/Board.java
  app/src/main/java/edu/up/cs/androidcatan/catan/graphics/HexagonGrid.java
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/game_trade_menu.xml
  app/src/main/res/layout/robber_discard_menu.xml
Labels: enhancement

#115 Alex's maid service 🎉 🎉 🎉
  .idea/codeStyles/codeStyleConfig.xml
  app/src/main/java/edu/up/cs/androidcatan/catan/CatanDumbComputerPlayer.java
  app/src/main/java/edu/up/cs/androidcatan/catan/Player.java
  app/src/main/java/edu/up/cs/androidcatan/catan/graphics/HexagonGrid.java
Labels: cleaning

#117 Alex fixed issue #116 - dumb ai
  app/src/main/java/edu/up/cs/androidcatan/catan/CatanDumbComputerPlayer.java
  app/src/main/java/edu/up/cs/androidcatan/catan/graphics/BoardSurfaceView.java
  app/src/main/java/edu/up/cs/androidcatan/catan/graphics/HexagonGrid.java
  app/src/main/java/edu/up/cs/androidcatan/catan/graphics/House.java
Labels: bug

#121 Alex - added touch support with highlighting
  app/src/main/java/edu/up/cs/androidcatan/catan/CatanGameState.java
  app/src/main/java/edu/up/cs/androidcatan/catan/CatanHumanPlayer.java
  app/src/main/java/edu/up/cs/androidcatan/catan/gamestate/Board.java
  app/src/main/java/edu/up/cs/androidcatan/catan/graphics/HexagonDrawable.java
  app/src/main/java/edu/up/cs/androidcatan/catan/graphics/HexagonGrid.java
  app/src/main/res/layout/activity_main.xml
Labels: feature

#122 Alex - game message
  app/src/main/java/edu/up/cs/androidcatan/catan/CatanHumanPlayer.java
  app/src/main/java/edu/up/cs/androidcatan/catan/graphics/BoardSurfaceView.java
  app/src/main/java/edu/up/cs/androidcatan/catan/graphics/HexagonDrawable.java
  app/src/main/java/edu/up/cs/androidcatan/catan/graphics/HexagonGrid.java
  app/src/main/java/edu/up/cs/androidcatan/catan/graphics/IntersectionDrawable.java
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/strings.xml
Labels: feature

#126 Alex chit adjacency rule
  app/src/main/java/edu/up/cs/androidcatan/catan/CatanHumanPlayer.java
  app/src/main/java/edu/up/cs/androidcatan/catan/gamestate/Board.java
  app/src/main/java/edu/up/cs/androidcatan/catan/graphics/HexagonGrid.java
Labels: feature

#128 Alex - port drawing
  app/src/main/java/edu/up/cs/androidcatan/catan/CatanHumanPlayer.java
  app/src/main/java/edu/up/cs/androidcatan/catan/gamestate/Port.java
  app/src/main/java/edu/up/cs/androidcatan/catan/graphics/BoardSurfaceView.java
  app/src/main/java/edu/up/cs/androidcatan/catan/graphics/HexagonGrid.java
  app/src/main/java/edu/up/cs/androidcatan/catan/graphics/Ports.java
  app/src/main/res/layout/activity_main.xml
  gradlew
  gradlew.bat
Labels: feature

#131 fixed id shuffling bug
  app/src/main/java/edu/up/cs/androidcatan/catan/gamestate/Board.java
Labels: bug

#135 Alex - building selection, chit adj. rule bug fix
  app/src/main/java/edu/up/cs/androidcatan/catan/CatanGameState.java
  app/src/main/java/edu/up/cs/androidcatan/catan/CatanHumanPlayer.java
  app/src/main/java/edu/up/cs/androidcatan/catan/gamestate/Board.java
  app/src/main/java/edu/up/cs/androidcatan/catan/graphics/HexagonGrid.java
Labels: bug, feature

#138 Alex implemented robber drawable
  app/src/main/java/edu/up/cs/androidcatan/catan/CatanHumanPlayer.java
  app/src/main/java/edu/up/cs/androidcatan/catan/graphics/HexagonDrawable.java
Labels: feature, graphics

#144 fixed the resource value glitch
  app/src/main/java/edu/up/cs/androidcatan/catan/CatanGameState.java
  app/src/main/java/edu/up/cs/androidcatan/catan/CatanHumanPlayer.java
Labels: bug

#149 Alex's Pest Extermination Service
  app/src/main/java/edu/up/cs/androidcatan/catan/CatanGameState.java
  app/src/main/java/edu/up/cs/androidcatan/catan/CatanHumanPlayer.java
  app/src/main/java/edu/up/cs/androidcatan/catan/Player.java
  app/src/main/java/edu/up/cs/androidcatan/catan/graphics/HexagonDrawable.java
  app/src/main/java/edu/up/cs/androidcatan/catan/graphics/HexagonGrid.java
  app/src/main/java/edu/up/cs/androidcatan/game/GameMainActivity.java
Labels: bug

#159 Alex - removing old menus
  app/src/main/java/edu/up/cs/androidcatan/catan/CatanHumanPlayer.java
Labels: cleaning

#161 Alex - fixed touch
  .idea/misc.xml
  app/src/main/java/edu/up/cs/androidcatan/catan/CatanHumanPlayer.java
  app/src/main/res/values/strings.xml
Labels: bug

#190 Alex moving state manipulation to local game
  app/src/main/java/edu/up/cs/androidcatan/catan/CatanGameState.java
  app/src/main/java/edu/up/cs/androidcatan/catan/CatanHumanPlayer.java
  app/src/main/java/edu/up/cs/androidcatan/catan/CatanLocalGame.java
  app/src/main/java/edu/up/cs/androidcatan/catan/actions/CatanBuildSettlementAction.java
  app/src/main/java/edu/up/cs/androidcatan/catan/gamestate/Board.java
Labels: cleaning, enhancement

#194 Alex port trading, bug fix
  app/src/main/java/edu/up/cs/androidcatan/catan/CatanGameState.java
  app/src/main/java/edu/up/cs/androidcatan/catan/CatanHumanPlayer.java
  app/src/main/java/edu/up/cs/androidcatan/catan/CatanLocalGame.java
  app/src/main/java/edu/up/cs/androidcatan/catan/actions/CatanTradeWithCustomPortAction.java
  app/src/main/java/edu/up/cs/androidcatan/catan/actions/CatanTradeWithPortAction.java
  app/src/main/java/edu/up/cs/androidcatan/catan/gamestate/Board.java
  app/src/main/java/edu/up/cs/androidcatan/catan/gamestate/Port.java
  app/src/main/java/edu/up/cs/androidcatan/catan/graphics/HexagonGrid.java
  app/src/main/res/values/strings.xml
Labels: bug, cleaning, feature

#196 Alex bug fix
  app/src/main/java/edu/up/cs/androidcatan/catan/CatanLocalGame.java
  app/src/main/java/edu/up/cs/androidcatan/catan/actions/CatanTradeAction.java
  app/src/main/java/edu/up/cs/androidcatan/catan/graphics/BoardSurfaceView.java
Labels: bug

#199 Alex fixed victory points bug
  app/src/main/res/layout/catan_main_activity.xml
  app/src/main/res/values/strings.xml
Labels: bug

#201 aesthetic changes to sidebar and scoreboard
  app/src/main/java/edu/up/cs/androidcatan/catan/CatanHumanPlayer.java
Labels: enhancement

#205 Alex fixing small bugs reported by Dr. Tribelhorn
  app/src/main/java/edu/up/cs/androidcatan/catan/Player.java
  app/src/main/java/edu/up/cs/androidcatan/catan/gamestate/Board.java
Labels: bug

#223 Alex
  .idea/misc.xml
  app/src/androidTest/java/edu/up/cs/androidcatan/test/BoardTest.java
  app/src/main/java/edu/up/cs/androidcatan/catan/CatanGameState.java
  app/src/main/java/edu/up/cs/androidcatan/catan/CatanHumanPlayer.java
  app/src/main/java/edu/up/cs/androidcatan/catan/CatanLocalGame.java
  app/src/main/java/edu/up/cs/androidcatan/catan/Player.java
  app/src/main/java/edu/up/cs/androidcatan/catan/gamestate/Board.java
  app/src/main/java/edu/up/cs/androidcatan/catan/gamestate/Graph.java
  app/src/main/res/layout/catan_main_activity.xml
Labels: bug, enhancement

#236 fixed all warnings in board test class
  app/src/androidTest/java/edu/up/cs/androidcatan/test/BoardTest.java
Labels: bug
